version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  kyoku:
    image: quay.io/miwa/kyoku
    volumes: 
      - "./music:/music"
    ports:
      - "3033:3000"
    env_file:
      - "docker.env"
    depends_on:
      - "db"